import { extension_settings } from '../../../extensions.js';
import { saveSettingsDebounced } from '../../../../script.js';

const EXT='LongFlow', MARK=Symbol.for('longflow.fetch-hook');
const DEF={enabled:true,smoothDisplay:true,smoothChunkChars:32,smoothDelayMs:18};
let originalFetch=null,lastOk=false;
function cfg(){extension_settings[EXT]??={};for(const[k,v]of Object.entries(DEF))if(extension_settings[EXT][k]===undefined)extension_settings[EXT][k]=v;return extension_settings[EXT]}
function toast(k,m){window.toastr?.[k]?.(m,'LongFlow')??console.log('[LongFlow]',m)}
function name(){const a=new Uint8Array(12);crypto.getRandomValues(a);return'lf_emit_'+[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function clone(x){return JSON.parse(JSON.stringify(x))}
function inject(body){const b=clone(body);if(!Array.isArray(b.messages))return null;const n=name();const tool={type:'function',function:{name:n,description:'Use this transport tool exactly once for the final user-visible answer. Put the complete final reply in content.',parameters:{type:'object',properties:{content:{type:'string'}},required:['content'],additionalProperties:false}}};b.tools=[...(Array.isArray(b.tools)?b.tools:[]),tool];if(b.tool_choice===undefined||b.tool_choice==='none')b.tool_choice='auto';const last=[...b.messages].reverse().find(m=>!['system','developer'].includes(m?.role))?.role;const msg={role:(last==='assistant'||last==='model'||!last)?'user':'system',content:`For the final user-visible reply, call the tool \`${n}\` exactly once. Put the entire final reply in its content argument and do not output user-visible text outside that tool call.`};b.messages.push(msg);return{body:b,tool:n,stream:b.stream===true}}
function parseArgs(s){if(s&&typeof s==='object')return typeof s.content==='string'?s.content:'';s=String(s??'');try{return JSON.parse(s)?.content??''}catch{}const m=/["']content["']\s*:\s*"/.exec(s);if(!m)return'';let x=s.slice(m.index+m[0].length),o='',e=false;for(let i=0;i<x.length;i++){const c=x[i];if(e){o+=({n:'\n',r:'\r',t:'\t','"':'"','\\':'\\'}[c]??c);e=false;continue}if(c==='\\'){e=true;continue}if(c==='"')break;o+=c}return o}
function outChunk(meta,text,finish=null){return{id:meta.id||'chatcmpl-longflow',object:'chat.completion.chunk',created:meta.created||Math.floor(Date.now()/1000),model:meta.model||'',choices:[{index:0,delta:text?{content:text}:{},finish_reason:finish}]}}
function splitText(s,c){if(!c.smoothDisplay)return[s];const n=Math.max(8,Math.min(256,Number(c.smoothChunkChars)||32)),a=[];for(let i=0;i<s.length;i+=n)a.push(s.slice(i,i+n));return a}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function streamResp(resp,tool,c){if(!resp.body)return resp;const reader=resp.body.getReader(),dec=new TextDecoder(),enc=new TextEncoder();let buf='',meta={},args='',seen=false,done=false,queue=[];const stream=new ReadableStream({async pull(ctrl){try{if(queue.length){const x=queue.shift();if(x.delay)await sleep(x.delay);ctrl.enqueue(enc.encode(`data: ${JSON.stringify(x.obj)}\n\n`));return}if(done){ctrl.enqueue(enc.encode('data: [DONE]\n\n'));ctrl.close();lastOk=seen;return}while(true){const r=await reader.read();if(r.done){done=true;const text=parseArgs(args);splitText(text,c).forEach((t,i)=>queue.push({obj:outChunk(meta,t),delay:i?Math.max(0,Number(c.smoothDelayMs)||18):0}));queue.push({obj:outChunk(meta,'','stop'),delay:0});if(queue.length)return this.pull(ctrl);continue}buf+=dec.decode(r.value,{stream:true}).replace(/\r\n/g,'\n');let p;while((p=buf.indexOf('\n\n'))>=0){const block=buf.slice(0,p);buf=buf.slice(p+2);const data=block.split('\n').filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trimStart()).join('\n');if(!data||data==='[DONE]')continue;let j;try{j=JSON.parse(data)}catch{continue}meta={id:j.id,created:j.created,model:j.model};for(const ch of j.choices||[]){for(const tc of ch?.delta?.tool_calls||[]){if(tc?.function?.name===tool||seen){seen=true;if(tc?.function?.arguments)args+=tc.function.arguments}}if(!seen&&ch?.delta?.content)queue.push({obj:outChunk(meta,ch.delta.content),delay:0})}}if(queue.length)return this.pull(ctrl)}}catch(e){ctrl.error(e)}}});const h=new Headers(resp.headers);h.delete('content-length');h.set('content-type','text/event-stream; charset=utf-8');return new Response(stream,{status:resp.status,statusText:resp.statusText,headers:h})}
async function nonStream(resp,tool){let j;try{j=await resp.json()}catch{return resp}for(const ch of j.choices||[]){const calls=ch?.message?.tool_calls||[];const hit=calls.find(x=>x?.function?.name===tool);if(hit){ch.message.content=parseArgs(hit.function.arguments);ch.message.tool_calls=calls.filter(x=>x!==hit);ch.finish_reason=ch.message.tool_calls.length?'tool_calls':'stop';lastOk=true}}return new Response(JSON.stringify(j),{status:resp.status,statusText:resp.statusText,headers:{'content-type':'application/json; charset=utf-8'}})}
function isTarget(input,init){try{const u=new URL(typeof input==='string'?input:input.url,location.href);return u.pathname==='/api/backends/chat-completions/generate'&&String(init?.method||'GET').toUpperCase()==='POST'}catch{return false}}
async function hooked(input,init){const c=cfg();if(!c.enabled||!isTarget(input,init)||typeof init?.body!=='string')return originalFetch.call(window,input,init);let b;try{b=JSON.parse(init.body)}catch{return originalFetch.call(window,input,init)}const q=inject(b);if(!q)return originalFetch.call(window,input,init);const r=await originalFetch.call(window,input,{...init,body:JSON.stringify(q.body)});if(!r.ok)return r;return q.stream?streamResp(r,q.tool,c):nonStream(r,q.tool)}
function install(){if(window.fetch?.[MARK])return;originalFetch=window.fetch;const f=(a,b)=>hooked(a,b);Object.defineProperty(f,MARK,{value:true});window.fetch=f}
function render(){if(document.getElementById('longflow_panel'))return;const host=document.querySelector('#extensions_settings2')||document.querySelector('#extensions_settings');if(!host)return;const c=cfg(),d=document.createElement('div');d.id='longflow_panel';d.innerHTML=`<div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header"><b>LongFlow</b></div><div class="inline-drawer-content longflow-content"><label class="checkbox_label"><input id="longflow_enabled" type="checkbox"><span id="longflow_enabled_text"></span></label><label class="checkbox_label"><input id="longflow_smooth" type="checkbox"><span>平滑显示</span></label><button id="longflow_test" class="menu_button">测试</button></div></div>`;host.appendChild(d);const e=d.querySelector('#longflow_enabled'),s=d.querySelector('#longflow_smooth'),t=d.querySelector('#longflow_enabled_text');e.checked=!!c.enabled;s.checked=!!c.smoothDisplay;const label=()=>t.textContent=e.checked?'已启动':'已停用';label();e.oninput=()=>{c.enabled=e.checked;label();saveSettingsDebounced()};s.oninput=()=>{c.smoothDisplay=s.checked;saveSettingsDebounced()};d.querySelector('#longflow_test').onclick=()=>toast(lastOk?'success':'info',lastOk?'LongFlow 工作正常。':'LongFlow 已启动，请先完成一次聊天后再测试。')}
export async function init(){cfg();install();render();console.log('[LongFlow] loaded')}
export async function onEnable(){install()}
export async function onDisable(){}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else queueMicrotask(init);
